# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181202_1626'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bio',
            new_name='Profile',
        ),
    ]
