# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 19:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tickets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='add_tickets_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('LOW', 'Low')], default='Low', max_length=15)),
                ('status', models.CharField(choices=[('NW', 'new'), ('UR', 'under-review'), ('DE', 'declined'), ('NM', 'needs-more-info'), ('PD', 'planned'), ('IP', 'in-progress'), ('CP', 'completed')], default='NW', max_length=2)),
                ('type', models.CharField(choices=[('BG', 'bugs'), ('FR', 'feature')], default='Bug', max_length=15)),
                ('views', models.IntegerField(default=0)),
                ('date_create', models.DateTimeField(blank=True, default=tickets.models.one_day_hence, null=True)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('comment_created', models.DateTimeField(blank=True, default=tickets.models.one_day_hence, null=True)),
                ('ticket', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tickets.add_tickets_form')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
