# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_form',
            name='ticket',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.add_tickets_form'),
        ),
    ]
