# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20181130_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_tickets_form',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('LOW', 'Low')], default='LOW', max_length=15),
        ),
    ]
