# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import tickets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20181201_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_tickets_form',
            name='last_seen',
            field=models.DateTimeField(default=tickets.models.one_day_hence),
        ),
    ]
