# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_add_tickets_form_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_tickets_form',
            name='status',
            field=models.CharField(choices=[('New', 'new'), ('Under_review', 'under-review'), ('Declined', 'declined'), ('Needs_more_info', 'needs-more-info'), ('Planned', 'planned'), ('In_Progress', 'in-progress'), ('Completed', 'completed')], default='New', max_length=2),
        ),
        migrations.AlterField(
            model_name='add_tickets_form',
            name='type',
            field=models.CharField(choices=[('BUG', 'bugs'), ('FEATURE', 'feature')], default='Bug', max_length=15),
        ),
    ]
