# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20181206_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_tickets_form',
            name='type',
            field=models.CharField(choices=[('Error', 'Error'), ('FEATURE', 'feature')], default='Error', max_length=20),
        ),
    ]
