# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20181206_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_tickets_form',
            name='type',
            field=models.CharField(choices=[('Bug', 'Bug'), ('FEATURE', 'feature')], default='Bug', max_length=20),
        ),
    ]
