# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 22:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20181206_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_tickets_form',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 6, 22, 32, 21, 326674, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='comment_form',
            name='comment_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 6, 22, 32, 21, 327371, tzinfo=utc), null=True),
        ),
    ]
