# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='like',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='like',
        ),
    ]
