# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 20:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_add_tickets_form_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_tickets_form',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
