# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_auto_20181210_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_tickets_form',
            name='likes',
        ),
    ]
