# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-15 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_remove_add_tickets_form_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_tickets_form',
            name='like_and_dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment_form',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
