# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-15 21:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0018_auto_20181215_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='likes_ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('like_and_dislike', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='add_tickets_form',
            name='like_and_dislike',
        ),
        migrations.AddField(
            model_name='likes_ticket',
            name='ticket',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='tickets.add_tickets_form'),
        ),
        migrations.AddField(
            model_name='likes_ticket',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
