# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_add_tickets_form_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_tickets_form',
            name='post_like',
        ),
    ]
