# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 20:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0022_remove_add_tickets_form_post_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='like_posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('issue', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='like_issue', to='tickets.add_tickets_form')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
